### PR TITLE
Add FC.blankit, function that will take all external links and add ta…

### PR DESCRIPTION
**Pull request by kyleatfine**
…rget _blank

Only thing I would consider adding is a check that the href isn't "#" to reserve for triggers, but if we're using e.preventDefault the target really won't matter.

### CODE REVIEW

**Comment by kyleatfine** [comment]
yeah, my thing to add might be necessary. Already ran into a bug with it because of that

**Comment by tshedor** [comment]
@kyleatfine you don't want to add this to FCH?

**Comment by kyleatfine** [comment]
I'm cool with it being in FCH, I wasn't sure where you thought this belonged.

**Comment by kyleatfine** [comment]
Regardless, I'm having an issue with relative links too, they all get target blank now

**Comment by tshedor** [comment]
Sounds like a good opportunity for Jasmine tests

**Comment by kyleatfine** [comment]
Alright, this has been redone. Function added to FCH.prototype, tests created. You do have to call FCH.blankit() if you want this to run.

**Pull request merged**
