### PR TITLE
Toggle class

### PR DESCRIPTION
**Pull request by kyleatfine**
adds a toggleClass function, adds and updates tests, updates README with descriptions for addClass, removeClass and toggleClass

### CODE REVIEW

**Comment by kyleatfine** [comment]
Failed test have to update more tests

**Comment by kyleatfine** [comment]
My tests pass, Travis CI's errors have to do with:
```
The command "eval npm install " failed 3 times.
The command "npm install " failed and exited with 1 during .
```

**Comment by tshedor** [comment]
Looks like the commits were doubled up in that rebase, but you know what, no conflicts and the tests are passing. Thanks for seeing this through @kyleshevlin

**Comment by kyleshevlin** [comment]
Cool, no problem. Glad to see it through.

**Pull request merged**
